# fullnameOverride: discovery-2
namespace: example-namespace
image: ghcr.io/primeintellect-ai/protocol/discovery:v0.3.1-beta.5
port: 8089

redis:
  enabled: true
  image: redis:7.0

api:
  pdb:
    enabled: true
    maxUnavailable: 1
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    metrics:
      cpu:
        enabled: true
        targetUtilization: 70
      memory:
        enabled: false

env:
  REDIS_URL: "redis://discovery-redis:6379"
  RPC_URL: "http://reth:8545"
  LOG_LEVEL: "info"
  LOCATION_SERVICE_URL: "https://ipapi.co"
  MAX_NODES_PER_IP: "2"

envFromSecret:
  - name: PLATFORM_API_KEY
    secretKeyRef:
      name: discovery-secret
      key: platformApiKey
  - name: LOCATION_SERVICE_API_KEY
    secretKeyRef:
      name: discovery-secret
      key: locationServiceApiKey

# TODO: fill in the secrets
secrets:
  platformApiKey: "FOO"
  locationServiceApiKey: "BAR"
