name: prime-dev
root: .
enable_pane_titles: true
windows:
  - services:
      layout: even-horizontal 
      panes:
        - Worker: bash -c 'sleep 5 && cd smart-contracts && sh deploy.sh && sh deploy_work_validation.sh && cd .. && make setup && clear'
        - Discovery: bash -c 'sleep 20 && make watch-discovery'
        - Validator: bash -c 'sleep 25 && make watch-validator'
        - Orchestrator: bash -c 'sleep 30 && make watch-orchestrator'
  - background:
      layout: even-horizontal
      panes:
        - "Prime Dev Services": bash -c 'docker compose up anvil redis'