name: prime-dev
root: .
enable_pane_titles: true
on_project_start: |
  docker compose up -d reth redis
  docker compose wait --timeout 180 reth redis
  cd smart-contracts && sh deploy.sh && sh deploy_work_validation.sh && cd ..
  make setup
windows:
  - services:
      layout: even-horizontal 
      panes:
        - Worker:
        - Discovery: make watch-discovery
        - Validator: make watch-validator
        - Orchestrator: make watch-orchestrator
  - background:
      layout: even-horizontal
      panes:
        - "Prime Dev Services": docker compose logs -f reth redis
