[workspace]
members = ["discovery", "worker", "validator", "shared", "orchestrator", "dev-utils"]
resolver = "2"

[workspace.package]
version = "0.2.3"
edition = "2021"

[workspace.features]
default = []
testnet = []
