version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command:
      - /usr/local/bin/etcd
      - --name=etcd0
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - etcd-net

  etcd-browser:
    image: buddho/etcd-browser:latest
    ports:
      - "8000:8000"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - SERVER_PORT=8000
      - ETCD_VERSION=v3
    networks:
      - etcd-net
    depends_on:
      - etcd

  coordinator:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
    environment:
      - ETCD_HOSTS=http://etcd:2379
    ports:
      - "3000:3000"
    networks:
      - etcd-net
    depends_on:
      - etcd

networks:
  etcd-net:
    driver: bridge