[package]
name = "validator"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4.9.0"
alloy = { version = "0.9.2", features = ["full"] }
clap = { version = "4.5.26", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.25"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.135"
shared = { path = "../shared" }
tokio = "1.43.0"
url = "2.5.4"
