- hosts: discovery
  become: yes
  gather_facts: no
  tasks:
    - name: Include common tasks
      include_tasks: ../tasks/common.yml

    - name: Include Redis setup tasks
      include_tasks: ../tasks/redis.yml

    - name: Include discovery setup tasks
      include_tasks: ../tasks/discovery_setup.yml

