- hosts: orchestrator 
  become: yes
  gather_facts: no
  tasks:
    - name: Include common tasks
      include_tasks: ../tasks/common/common.yml

    - name: Include Redis setup tasks
      include_tasks: ../tasks/common/redis.yml

    - name: Include orchestrator setup tasks
      include_tasks: ../tasks/orchestrator_setup.yml


