- hosts: discovery
  become: yes
  gather_facts: no
  tasks:
    - name: Include common tasks
      include_tasks: ../tasks/common.yml

    - name: Include validatory setup tasks
      include_tasks: ../tasks/validatory_setup.yml

