{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bootnode.fullname" . }}-secrets
  namespace: {{ include "bootnode.namespace" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
