---
- name: Debug variables
  debug:
    msg: 
      - "Validator Address: {{ validator_address }}"
      - "RPC URL: {{ rpc_url }}"
      - "Ansible User: {{ ansible_user }}"
- name: Create discovery directory
  file:
    path: "/opt/prime/discovery"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Download discovery binary
  get_url:
    url: "https://storage.googleapis.com/prime-protocol/{{ version }}/discovery-linux-x86_64"
    dest: "/opt/prime/discovery/discovery"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Remove existing discovery service files
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/prime-discovery.service
    - /etc/systemd/system/prime-discovery.service.bak
- name: Create systemd service file for discovery
  become: yes
  template:
    src: ../templates/discovery.service.j2
    dest: /etc/systemd/system/prime-discovery.service
    mode: '0644'
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Stop discovery service if running
  systemd:
    name: prime-discovery
    state: stopped
  ignore_errors: yes
- name: Start and enable discovery service
  systemd:
    name: prime-discovery
    state: restarted
    enabled: yes
