---
- name: Create discovery directory
  file:
    path: "/opt/prime/discovery"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Copy discovery binary
  copy:
    src: "../../target/release/discovery"
    dest: "/opt/prime/discovery/discovery"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Create systemd service file for discovery
  template:
    src: ../templates/discovery.service.j2
    dest: /etc/systemd/system/prime-discovery.service
    mode: '0644'
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Start and enable discovery service
  systemd:
    name: prime-discovery
    state: started
    enabled: yes
