namespace: example-namespace
image: ghcr.io/primeintellect-ai/protocol/validator:v0.1.8-beta.30
computePoolId: "1"

env:
  RPC_URL: "http://anvil.example-namespace:8545"
  DISCOVERY_URLS: "http://discovery.example-namespace:8089"
  BUCKET_NAME: "example-development-bucket"
  LOG_LEVEL: "info"
  TOPLOC_GRACE_INTERVAL: "1"
  TOPLOC_WORK_VALIDATION_INTERVAL: "35"
  # Number of triggers per validation iteration to toploc server
  BATCH_TRIGGER_SIZE: "10"
  DISABLE_HARDWARE_VALIDATION: "true"
  VALIDATOR_PENALTY: "200"
  INCOMPLETE_GROUP_GRACE_PERIOD_MINUTES: "0"
  TOPLOC_CONFIGS: |
    []
  # In case we use an external redis
  REDIS_URL: "redis://redis-master.example-namespace:6379"

secrets:
  validatorKey: "private key"
  validatorApiKey: "your-secure-api-key-here"
  s3Credentials: "base64EncodedS3CredentialsGoHere"