namespace: example-namespace
image: ghcr.io/primeintellect-ai/protocol/validator:v0.1.8-beta.30
computePoolId: "1"

env:
  RPC_URL: "http://anvil.example-namespace:8545"
  DISCOVERY_URL: "http://discovery.example-namespace:8089"
  BUCKET_NAME: "example-development-bucket"
  LOG_LEVEL: "info"
  TOPLOC_SERVER_URL: "https://example-service.example.io"
  TOPLOC_GRACE_INTERVAL: "1"
  TOPLOC_WORK_VALIDATION_INTERVAL: "35"
  DISABLE_HARDWARE_VALIDATION: "true"

secrets:
  validatorKey: "private key"
  toplocAuthToken: "exampleAuthTokenHere"
  s3Credentials: "base64EncodedS3CredentialsGoHere"
