version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  discovery:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RPC_URL=http://host.docker.internal:8545
    ports:
      - "8089:8089"
    networks:
      - redis-net
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm test
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=test
    depends_on:
      - redis
    networks:
      - redis-net
    profiles:
      - test
    volumes:
      - ./:/app

networks:
  redis-net:
    driver: bridge

volumes:
  redis-data: