apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "validator.fullname" . }}
  namespace: {{ include "validator.namespace" . }}
spec:
  healthCheck:
    type: HTTP
    requestPath: /health
    port: {{ .Values.port }}
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
