{{- if not .Values.env.REDIS_URL }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}
  namespace: {{ include "validator.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "validator.redisName" . }}
  template:
    metadata:
      labels:
        app: {{ include "validator.redisName" . }}
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: redis-data
              mountPath: /data
          command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "validator.fullname" . }}-redis-data
{{- end }}
