apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.secretName" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  validatorKey: {{ .Values.secrets.validatorKey | b64enc }}
  toplocAuthToken: {{ .Values.secrets.toplocAuthToken | b64enc }}
  s3Credentials: {{ .Values.secrets.s3Credentials | b64enc }}
