apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.secretName" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  validatorKey: {{ .Values.secrets.validatorKey | b64enc }}
  validatorApiKey: {{ .Values.secrets.validatorApiKey | b64enc }}
  {{- if .Values.secrets.s3Credentials }}
  s3Credentials: {{ .Values.secrets.s3Credentials | b64enc }}
  {{- end }}
