apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "validator.fullname" . }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "validator.backendConfigName" . }}"}'
spec:
  selector:
    app: {{ include "validator.fullname" . }}
  ports:
    - port: 9879
      targetPort: 9879
