apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}
  namespace: {{ include "validator.namespace" . }}
  labels:
    app: {{ include "validator.fullname" . }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "validator.fullname" . }}"}'
spec:
  selector:
    app: {{ include "validator.fullname" . }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
