apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}
  namespace: {{ include "validator.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "validator.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "validator.fullname" . }}
    spec:
      containers:
        - name: validator
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            capabilities:
              drop:
              - NET_RAW
          env:
            {{- if .Values.computePoolId }}
            - name: POOL_ID
              value: "{{ .Values.computePoolId | quote }}"
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.envFromSecret }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretKeyRef.name }}
                  key: {{ .secretKeyRef.key }}
            {{- end -}}
