apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.fullname" . }}
  namespace: {{ include "orchestrator.namespace" . }}
  labels:
    app: {{ include "orchestrator.fullname" . }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "orchestrator.fullname" . }}-backend-config"}'
spec:
  selector:
    app: {{ include "orchestrator.fullname" . }}-api
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.fullname" . }}-api
  namespace: {{ include "orchestrator.namespace" . }}
  labels:
    app: {{ include "orchestrator.fullname" . }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "orchestrator.fullname" . }}-backend-config"}'
spec:
  selector:
    app: {{ include "orchestrator.fullname" . }}-api
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
