{{- if .Values.api.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "orchestrator.fullname" . }}-api
  namespace: {{ include "orchestrator.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "orchestrator.fullname" . }}-api
  minReplicas: {{ .Values.api.hpa.minReplicas }}
  maxReplicas: {{ .Values.api.hpa.maxReplicas }}
  {{- if or .Values.api.hpa.metrics.cpu.enabled .Values.api.hpa.metrics.memory.enabled }}
  metrics:
  {{- if .Values.api.hpa.metrics.cpu.enabled }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.api.hpa.metrics.cpu.targetUtilization }}
  {{- end }}
  {{- if .Values.api.hpa.metrics.memory.enabled }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.api.hpa.metrics.memory.targetUtilization }}
  {{- end }}
  {{- end }}
  {{- end }}
