apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "orchestrator.backendConfigName" . }}
  namespace: {{ .Values.namespace }}
spec:
  healthCheck:
    type: HTTP
    requestPath: /health
    port: 8090
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
