apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "orchestrator.backendConfigName" . }}"}'
spec:
  selector:
    app: {{ include "orchestrator.fullname" . }}
  ports:
    - port: 8090
      targetPort: 8090
