apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchestrator.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "orchestrator.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "orchestrator.fullname" . }}
    spec:
      containers:
        - name: orchestrator
          image: {{ .Values.image }}
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: URL
              value: {{ .Values.url }}
            - name: RPC_URL
              value: {{ .Values.env.RPC_URL }}
            - name: REDIS_STORE_URL
              value: "redis://{{ include "orchestrator.redisName" . }}:6379"
            - name: DISCOVERY_URL
              value: {{ .Values.env.DISCOVERY_URL }}
            - name: COORDINATOR_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "orchestrator.secretName" . }}
                  key: coordinatorKey
            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "orchestrator.secretName" . }}
                  key: adminApiKey
            - name: S3_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ include "orchestrator.secretName" . }}
                  key: s3Credentials
            - name: COMPUTE_POOL_ID
              value: "{{ .Values.computePoolId }}"
            - name: DOMAIN_ID
              value: "{{ .Values.domainId }}"
            - name: DISCOVERY_REFRESH_INTERVAL
              value: "{{ .Values.env.DISCOVERY_REFRESH_INTERVAL }}"
            - name: BUCKET_NAME
              value: "{{ .Values.env.BUCKET_NAME }}"
            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL }}"
            - name: HOURLY_S3_UPLOAD_LIMIT
              value: "{{ .Values.env.HOURLY_S3_UPLOAD_LIMIT }}"
            {{- if .Values.env.WEBHOOK_URLS }}
            - name: WEBHOOK_URLS
              value: "{{ .Values.env.WEBHOOK_URLS }}"
            {{- end }}
