apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.fullname" . }}-processor
  namespace: {{ include "orchestrator.namespace" . }}
  labels:
    app: {{ include "orchestrator.fullname" . }}-processor
spec:
  selector:
    app: {{ include "orchestrator.fullname" . }}-processor
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
