{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchestrator.fullname" . }}-redis
  namespace: {{ include "orchestrator.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "orchestrator.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "orchestrator.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: {{ include "orchestrator.fullname" . }}-redis-data
              mountPath: /data
          command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
      volumes:
        - name: {{ include "orchestrator.fullname" . }}-redis-data
          persistentVolumeClaim:
            claimName: {{ include "orchestrator.fullname" . }}-redis-data
{{- end }}
