{{- if not .Values.env.REDIS_URL }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "orchestrator.redisPVCName" . }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}