apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.redisName" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "orchestrator.redisName" . }}
  ports:
    - port: 6379
      targetPort: 6379
