apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestrator.secretName" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  coordinatorKey: {{ .Values.secrets.coordinatorKey | b64enc }}
  adminApiKey: {{ .Values.secrets.adminApiKey | b64enc }}
  s3Credentials: {{ .Values.secrets.s3Credentials | b64enc }}
