name: Check Format & Lint

on:
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - '**.rs'
      - '**/Cargo.*'
  push:
    branches: [ main, master, develop ]
    paths:
      - '**.rs'
      - '**/Cargo.*'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-C debuginfo=0"

jobs:
  check:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.83.0 
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "**/target"
          cache-on-failure: true
          
      - name: Run format check
        run: cargo fmt -- --check

      - name: Run clippy
        if: success() || failure()  # Run even if fmt fails
        run: cargo clippy -- -D warnings

      - name: Run tests
        if: success() || failure()  # Run even if previous steps fail
        run: cargo test --verbose