name: Release on Demand

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Bump version and create tag
        id: bump
        run: |
          # Get current version
          CURRENT=$(grep '^version =' Cargo.toml | head -n 1 | cut -d '"' -f 2)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          
          # Bump version
          case "${{ github.event.inputs.bump }}" in
            major) ((MAJOR++)); MINOR=0; PATCH=0 ;;
            minor) ((MINOR++)); PATCH=0 ;;
            patch) ((PATCH++)) ;;
          esac
          
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          
          # Update Cargo.toml
          sed -i "s/version = \".*\"/version = \"${NEW_VERSION}\"/" Cargo.toml
          
          # Commit and tag
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "chore: release v${NEW_VERSION}"
          git push
          
          # Create tag (this triggers prod release)
          git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
          git push origin "v${NEW_VERSION}"
          
          echo "Released version v${NEW_VERSION}"